name: edu4dev
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.20.0
  firebase_storage: ^11.4.0
  flutter_bloc: ^8.1.3
  flutter_gen: ^5.3.2
  auto_route: ^7.8.4
  #localization
  intl: ^0.18.1
  dots_indicator: ^3.0.0
  # hive
  hive_generator: ^2.0.1
  flavor: ^2.0.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  firebase_auth: ^4.12.0
  cloud_firestore: ^4.12.1
  bloc: ^8.1.2
  equatable: ^2.0.5
  fluttertoast: ^8.2.2
  firebase_crashlytics: ^3.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.3.2
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  freezed: ^2.4.5
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
 
  assets:
    - assets/images/png/
