// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6iwPNEmn4dgzgwGzKjLinmRMqw0BYDjY',
    appId: '1:106663950932:web:4e69fef2293f6822e1cbc1',
    messagingSenderId: '106663950932',
    projectId: 'edu4dev-466e0',
    authDomain: 'edu4dev-466e0.firebaseapp.com',
    storageBucket: 'edu4dev-466e0.appspot.com',
    measurementId: 'G-9M6SHX0YHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAvoylZ3k3gllWKDoP2O0NbSByuRJHbxU',
    appId: '1:106663950932:android:f97df8bf3bea8ff7e1cbc1',
    messagingSenderId: '106663950932',
    projectId: 'edu4dev-466e0',
    storageBucket: 'edu4dev-466e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrm8fYMALYpnqXg3JMtVX371R4r9XqfS0',
    appId: '1:106663950932:ios:3d04e3dae0f36c79e1cbc1',
    messagingSenderId: '106663950932',
    projectId: 'edu4dev-466e0',
    storageBucket: 'edu4dev-466e0.appspot.com',
    iosBundleId: 'com.example.edu4dev',
  );
}
